### ISSUE TITLE
Expose rapp implementation information

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#226]
I just created a rapp implementation for a virtual rapp, i.e. `robosem_rapps/teleop` for `rocon_apps/teleop`.

Now, when starting the app manager it is registered as `rocon_apps/teleop` instead of `robosem_rapps/teleop`.

Outputs:

When starting up the rapp manager:

```
[INFO] [WallTime: 1399026284.494507] Rapp Manager : 'rocon_apps/teleop' added to the list of runnable apps.
```

Calling `list_rapps`:

```
available_rapps: 
[...]
  - 
    name: rocon_apps/teleop
    display_name: Robosem Teleop
    description: Teleoperation for Robosem
    compatibility: rocon:/robosem
    status: Ready
    icon: 
      resource_name: ''
      format: png
    required_capabilities: ['std_capabilities/DifferentialMobileBase', 'std_capabilities/RGBDSensor']
```

@stonier @jihoonl is this supposed to be that way?
